### ISSUE TITLE
[Critical] Security issue with "vm2"

### ISSUE THREAD

**Issue by vergjor** [joshweir/cdk-pretty-diff#10]
## What is the issue?

At work we use `cdk-pretty-diff` in multiple repositories and we seem to be finding security issues with `vm2`. 
This seems to be a nested dependency of `proxy-agent` which is also used in this package.

<img width="227" alt="image" src="https://github.com/joshweir/cdk-pretty-diff/assets/86774177/327562e3-4fd5-4945-ba96-94eff8c4e5c8">

## What could resolve this?

The main issue is that this package uses `proxy-agent@5.0.0`, and upgrading to `proxy-agent@6.3.0` should resolve this

https://github.com/TooTallNate/proxy-agents/releases/tag/proxy-agent%406.3.0

**Comment by gabrielenosso** [comment]
Up.
Need this fixed ASAP for CI/CD Pipeline which recognizes this as a Critical risk

**Comment by joshweir** [comment]
Unfortunately `cdk-pretty-diff` relies on the `proxy-agent` used by `aws-cdk`, looks like they are fixing it in this [issue](https://github.com/aws/aws-cdk/issues/26417). Once a fixed version is available i'll update this dependency. Without a fix from `aws-cdk`, updating this dependency will break `cdk-pretty-diff`

**Comment by joshweir** [comment]
v2.2.1 published to npm
