### ISSUE TITLE
Cannot find module 'aws-cdk/lib/api/cloudformation-deployments'

### ISSUE THREAD

**Issue by halfmu** [joshweir/cdk-pretty-diff#8]
```
Cannot find module 'aws-cdk/lib/api/cloudformation-deployments' from 'node_modules/cdk-pretty-diff/dist/cdk-reverse-engineered.js'
```

aws-cdk: 2.80.0
cdk-pretty-diff: 2.1.0

Since aws-cdk 2.80.0, I got the above errors when using cdk-pretty-diff.  Looks like it was renamed:
https://github.com/aws/aws-cdk/compare/v2.79.1...v2.80.0#diff-1c33e80dabddc5697544f07e314339fa3abe37c68183cb882ce5127b76f7deee

**Comment by joshweir** [comment]
This should now be fixed in [latest version](https://www.npmjs.com/package/cdk-pretty-diff) `v2.2.0`

**Comment by halfmu** [comment]
Thanks!
